#' @title 
#' EM
#' 
#' @description 
#' Estimates smoking score using Elliott Method. 
#' 
#' @param dataset
#' A data matrix of normalised methylation values in beta scale, with rows labelling the CpG probe ids and columns labelling the sample names.
#' Missing CpGs are excluded from the smoking score calculation.
#' eg: dummyBetaData
#' 
#' @param ref.Elliott 
#' This is used in "EM" and "all" methods. It is a dataframe with 187 CpGs and the effect sizes used to calculate the smoking score
#' proposed by Elliott et al PMID: 24485148.
#' 
#' @return 
#' Returns a result object with smoking score generated by following approach outlined in Elliott et al PMID: 24485148.
#' 
#' @examples 
#' data(dummyBetaData)
#' data(Illig_data)
#' result <- epismoker(dataset = dummyBetaData, ref.Elliott = Illig_data, method = "EM")
#' ## result contains smoking score calculated using EM.
#' @export
#'  
load("/projects/smokingscore/illig.RData")
EM <- function(dataset, ref.Elliott)
{
  message("=================================")
  message("<<<<< Elliot Method Started >>>>>")
  message("=================================")
  l <- dim(ref.Elliott)[1]
  dataset_EM <- dataset
  missingCpGs <- setdiff(ref.Elliott$cpgs, rownames(dataset_EM))
  ref.Elliott <- subset(ref.Elliott, cpgs %in% rownames(dataset_EM))
  m <- dim(ref.Elliott)[1]
  dataset_EM <-  dataset_EM[ref.Elliott$cpgs,]
  message(sprintf("Dataset has %s of %s CpGs required for smoking status estimation.",m,l))
  if (l!= m) {message( paste(missingCpGs, "is missing from the input dataset."))}
  stopifnot(rownames(dataset_EM) == ref.Elliott$cpgs)
  # Take difference between the reference beta and input beta
  dataset2 <- cbind(dataset_EM, ref.Elliott)
  betaDiff <- function(beta,effect, refBeta) {ifelse(effect >=0, beta-refBeta, refBeta - beta)}
  betas <- apply(dataset_EM, 2, betaDiff, dataset2$all_effect, dataset2$reference_never_median_beta_all)
  colnames(betas) <- colnames(dataset_EM)
  rownames(betas) <- rownames(dataset_EM)
  rm(dataset_EM)
  # For each sample, multiply betas with their respective weights and take sum of the products for all the available CpGs to make the smoking score.
  stopifnot(rownames(betas)== ref.Elliott$cpgs)
  res_EM <- setNames(data.frame(colnames(betas),apply(betas,2,SmokingScore, dataset2$weights)), c("SampleName","smokingscore_EM"))
  message("====================================")
  message("<<<<< Elliot Method Completed >>>>>")
  message("====================================")
  return(data.frame(res_EM))
}

SmokingScore <- function(betas, weights) {sum(t(betas) %*% weights)}