#' @title 
#' ZM
#' 
#' @description 
#' Estimates methylation score using Zhang Method. 
#' 
#' @param dataset
#' A data matrix of normalised methylation values in beta scale, with rows labelling the CpG probe ids and columns labelling the sample names.
#' Missing CpGs are excluded from the methylation score calculation.
#' eg: dummyBetaData
#' 
#' @param ref.Zhang
#' This is used in "ZM" and "all" methods. It is a dataframe with 4 CpGs and weights used to calculate methylation score proposed by Zhang et al PMID: 26826776.
#' 
#' @return 
#' Returns a result object with smoking score generated by following approach outlined in Zhang et al PMID: 26826776.
#' 
#' @examples 
#' data(dummyBetaData)
#' data(Illig_data)
#' result <- epismoker(dataset = dummyBetaData, ref.Elliott = Illig_data, method = "EM")
#' ## result contains smoking score calculated from ZM.
#' @export
#'  
load("/projects/smokingscore/Zhangetal_data.RData")
ZM <- function(dataset, ref.Zhang){
  message("================================")
  message("<<<<< Zhang Method Started >>>>>")
  message("=================================")
  dataset_ZM <- dataset
  cpgs <- intersect(rownames(dataset_ZM) , names(ref.Zhang))
  message(sprintf("Dataset has %s of %s CpGs required for Zhang et al method",length(cpgs),length(ref.Zhang)))
  dataset_ZM <- dataset_ZM[names(ref.Zhang),]
  # check if the order colnames of dataset equal to names(weights)
  stopifnot(rownames(dataset_ZM) == names(ref.Zhang))
  res_ZM <- setNames(data.frame(colnames(dataset_ZM),apply(dataset_ZM,2,SmokingScore, ref.Zhang)), c("SampleName","smokingscore_ZM"))
  rm(dataset_ZM)
  message("==================================")
  message("<<<<< Zhang Method Completed >>>>>")
  message("==================================")
  return(data.frame(res_ZM))
}

SmokingScore <- function(betas, weights) {sum(t(betas) %*% weights)}
